# NumPy
Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.

In [13]:
L = list(range(10))

print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
M= [str(c) for c in L]

print(M)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [15]:
N = [type(item) for item in L]
O = [type(item) for item in M]

print("Data type in L:",N)
print("Data type in M:", O)

Data type in L: [<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]
Data type in M: [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


### Array creation

In [12]:
import numpy as np

Array1 = np.zeros(10, dtype='int')
print(Array1)

[0 0 0 0 0 0 0 0 0 0]


In [16]:
np.ones((3,5), dtype='float') #3 rows, 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3,5), 1.32) #full matrix with predefined value '1.32'

array([[1.32, 1.32, 1.32, 1.32, 1.32],
       [1.32, 1.32, 1.32, 1.32, 1.32],
       [1.32, 1.32, 1.32, 1.32, 1.32]])

In [21]:
x = np.arange(0,20,2) #set sequence array. Starts with 0 to before 20 with increment of 2
print(x)
y = np.arange(5, 100, 25)
print(y)
z = np.arange(3, 100)
print(z)

[ 0  2  4  6  8 10 12 14 16 18]
[ 5 30 55 80]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]


In [27]:
#create an array of even space between the given range of values

a = np.linspace(0, 1, 5)
print(a)

b = np.linspace(5, 10, 3)
print(b)

c = np.linspace(0, 1) #Default interval space returned is 50 (including 0 and 1)
print(c)

[0.   0.25 0.5  0.75 1.  ]
[ 5.   7.5 10. ]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [29]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension

np.random.normal(0,1,(3,3))

#Standard deviation is a measure that is used to quantify the 
#amount of variation or dispersion of a set of data values

array([[-1.60860194, -0.65517745, -0.7207303 ],
       [ 0.27709647,  1.03810715,  0.83667067],
       [-0.68873262,  0.81468821,  0.02292806]])

In [31]:
#identity matrix

np.eye(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
#set a random seed

np.random.seed(0) 

x1 = np.random.randint(10, size=6) # 6 numbers ranges below 10
x2 = np.random.randint(10, size=(3,4)) # 2D Array
x3 = np.random.randint(10, size=(3,4,5)) # 3D array (3 arrays, 4 rows, 5 colums)

print("1D:", x1)
print("2D:", x2)
print("3D:", x3)

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

1D: [5 0 3 3 7 9]
2D: [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3D: [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


With the seed reset (every time), the same set of numbers will appear every time.

If the random seed is not reset, different numbers appear with every invocation

In [49]:
np.random.seed(0) 

x4 = np.random.randint(10, size=(3,4)) # 6 numbers ranges below 10

print (x4)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [50]:
np.random.seed(10) 

x4 = np.random.randint(10, size=(3,4)) # 6 numbers ranges below 10

print (x4)

[[9 4 0 1]
 [9 0 1 8]
 [9 0 8 6]]


In [51]:
np.random.seed(0) 

x4 = np.random.randint(10, size=(3,4)) # 6 numbers ranges below 10

print (x4)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [52]:
np.random.seed(10) 

x4 = np.random.randint(10, size=(3,4)) # 6 numbers ranges below 10

print (x4)

[[9 4 0 1]
 [9 0 1 8]
 [9 0 8 6]]


### Array Indexing

In [56]:
x1 = np.array([2,3,4,4,8,4])

print(x1[0])
print(x1[-1])
print(x1[4])
print(x1[-2])

2
4
8
8


In [57]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [58]:
x2[0,0]

3

In [59]:
x2[0,1]

5

In [60]:
x2[1,0]

7

In [62]:
x2[1,2] #should give out 8

8

In [63]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [64]:
x3[1, 2,3] #should give out 4

4

Hells yeah

In [65]:
x2[0,0] = 12 #value be replacin'

In [66]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Hells to the yeah

### Array Slicing

In [69]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
x[:5] #from start to before index 5

array([0, 1, 2, 3, 4])

In [73]:
x[4:] #from index 4 to end array

array([4, 5, 6, 7, 8, 9])

In [74]:
x[4:7] #from index 4 to before index 7

array([4, 5, 6])

In [75]:
x[:] #all elements 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x[: :2] #all elements step 2

array([0, 2, 4, 6, 8])

In [77]:
x[1: : 2] #from index 1 to end, step 2

array([1, 3, 5, 7, 9])

In [78]:
x[::-1] #reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Array Concatenation

In [83]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [21,21,21]

np.concatenate([x,y,z]) #np.concatenate([Arrays])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [86]:
grid = np.array([[1,2,3],[4,5,6]])

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
np.concatenate([grid, grid], axis=1) 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [94]:
np.concatenate([grid, grid], axis=2) 

AxisError: axis 2 is out of bounds for array of dimension 2

In [89]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [90]:
np.concatenate([x3, x3])

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]],

       [[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [91]:
np.concatenate([x3, x3], axis=1)

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7],
        [8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1],
        [0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4],
        [4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [92]:
np.concatenate([x3, x3], axis=2)

array([[[8, 1, 5, 9, 8, 8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3, 9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8, 5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7, 1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0, 0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7, 4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5, 2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1, 5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1, 4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6, 7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5, 7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4, 9, 4, 4, 6, 4]]])

In [93]:
np.concatenate([x3, x3], axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3

To combine a 2D array with 1D array, you can use np.vstack or np.hstack to do the task.

In [95]:
x = np.array([3,4,5])
apple = np.array([[1,2,3],[17,18,19]])

np.vstack([x, apple])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [96]:
np.hstack([x, apple])

ValueError: all the input arrays must have same number of dimensions

In [99]:
z = np.array([[9],[9]])

np.hstack([apple, z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [101]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [111]:
x1,x2,x3 = np.split(x,[3,6]) 

print(x1, x2, x3)

[0 1 2] [3 4 5] [6 7 8 9]


In [121]:
y = np.arange(30)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [123]:
y1, y2, y3 = np.split(y, [2,0])

print(y1, y2, y3)

[0 1] [] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [124]:
y1, y2, y3 = np.split(y, [2,1])

print(y1, y2, y3)

[0 1] [] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [125]:
y1, y2, y3 = np.split(y, [2,2])

print(y1, y2, y3)

[0 1] [] [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]


In [126]:
y1, y2, y3 = np.split(y, [2,10])

print(y1, y2, y3)

[0 1] [2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [127]:
y1, y2, y3 = np.split(y, [10,0])

print(y1, y2, y3)

[0 1 2 3 4 5 6 7 8 9] [] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [128]:
y1, y2, y3 = np.split(y, [5,10])

print(y1, y2, y3)

[0 1 2 3 4] [5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [129]:
y1, y2, y3 = np.split(y, [10,20]) #split array Y. First sub array has 10 values, 
                                  #the last sub array has value starts at index 20

print(y1, y2, y3)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19] [20 21 22 23 24 25 26 27 28 29]


In [144]:
z = np.arange(200)

z1,zz, zzz = np.split(z, [10,20]) #You can only split into 3 sub arrays

print(z1,zz,zzz)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19] [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]


Nailed it!

In [145]:
x4,x5,x6 = np.array_split(x,3) #can use integer

print(x4,x5,x6)

[0 1 2 3] [4 5 6] [7 8 9]


In [113]:
grid = np.arange(16).reshape((4,4))

print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [114]:
upper, lower = np.vsplit(grid,[2])

print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [115]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [116]:
left, right = np.hsplit(grid, [2])

In [117]:
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [118]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
