#### Create a dataframe

In [1]:
import pandas as pd

#create dataframe

data = pd.DataFrame({ 'Country': ['Russia', 'Colombia', 'Chile', 'Equador', 'Nigeria'],
                      'Rank': [121, 40, 100, 130, 11]
                    })

In [3]:
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [4]:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [8]:
new_data = pd.DataFrame({ 'group': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'],
                          'ounces': [4,3,12,6,7.5,8,3,5,6]
                        })

new_data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [10]:
new_data.sort_values(by=['ounces'], ascending=True, inplace=False) #inplace = True will make changes to the data

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [11]:
new_data.sort_values(by=['group', 'ounces'], ascending=[True,False], inplace=False)

group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [13]:
data = pd.DataFrame({ 'k1':['one']*3 + ['two']*4,
                      'k2' : [3,2,1] + [3]*2 + [4]*2
                    })

data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [14]:
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [16]:
#remove duplicates

data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [17]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

In [19]:
data = pd.DataFrame({ 'food':['rendang ayam', 'butter chicken', 'rendang ayam', 'Pastrami', 'corned beef',
                             'Rendang Ayam', 'pastrami', 'korma ayam', 'nova lox' ],
                      'ounces':[4,3,12,6,7.5,8,3,5,6]
                    })

data #Notice that the names of the food are not in uniform. Some has capital letter

food  ounces
0    rendang ayam     4.0
1  butter chicken     3.0
2    rendang ayam    12.0
3        Pastrami     6.0
4     corned beef     7.5
5    Rendang Ayam     8.0
6        pastrami     3.0
7      korma ayam     5.0
8        nova lox     6.0

#### Create New Variable

In [20]:
#create new variable that map which animal the food came from. There are a few ways. The first method is as below:

#1. Create a dictionary
meat_to_animal={
    'rendang ayam' : 'chicken',
    'butter chicken' : 'chicken',
    'pastrami' : 'cow',
    'corned beef' : 'cow',
    'korma ayam' : 'chicken',
    'nova lox' : 'salmon'
}

#2. Create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)


In [21]:
data

food  ounces   animal
0    rendang ayam     4.0  chicken
1  butter chicken     3.0  chicken
2    rendang ayam    12.0  chicken
3        Pastrami     6.0      cow
4     corned beef     7.5      cow
5    Rendang Ayam     8.0  chicken
6        pastrami     3.0      cow
7      korma ayam     5.0  chicken
8        nova lox     6.0   salmon

In [41]:
#Second way to add and map new variable in a table

#1. Define a function that maps food to animal

def meat2animal(series):
    if series['food'] == 'rendang ayam':
        return 'chicken'
    elif series['food'] == 'butter chicken':
        return 'chicken'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'korma ayam':
        return 'chicken'
    else:
        return 'salmon'
    
#2. convert the food values to the lower case

lower = lambda x: x.lower()

data['food'] = data['food'].apply(lower)

#3. apply the function

data['animal2'] = data.apply(meat2animal, axis='columns')

#pandas.DataFrame.apply(func)

In [42]:
data

food  ounces   animal  animal2
0    rendang ayam     4.0  chicken  chicken
1  butter chicken     3.0  chicken  chicken
2    rendang ayam    12.0  chicken  chicken
3        pastrami     6.0      cow      cow
4     corned beef     7.5      cow      cow
5    rendang ayam     8.0  chicken  chicken
6        pastrami     3.0      cow      cow
7      korma ayam     5.0  chicken  chicken
8        nova lox     6.0   salmon   salmon

In [43]:
#Another method is using assign function

data.assign(new_variable = data['ounces']*10)

food  ounces   animal  animal2  new_variable
0    rendang ayam     4.0  chicken  chicken          40.0
1  butter chicken     3.0  chicken  chicken          30.0
2    rendang ayam    12.0  chicken  chicken         120.0
3        pastrami     6.0      cow      cow          60.0
4     corned beef     7.5      cow      cow          75.0
5    rendang ayam     8.0  chicken  chicken          80.0
6        pastrami     3.0      cow      cow          30.0
7      korma ayam     5.0  chicken  chicken          50.0
8        nova lox     6.0   salmon   salmon          60.0

In [44]:
data.drop('animal2', axis='columns', inplace=True)

In [45]:
data

food  ounces   animal
0    rendang ayam     4.0  chicken
1  butter chicken     3.0  chicken
2    rendang ayam    12.0  chicken
3        pastrami     6.0      cow
4     corned beef     7.5      cow
5    rendang ayam     8.0  chicken
6        pastrami     3.0      cow
7      korma ayam     5.0  chicken
8        nova lox     6.0   salmon

#### Missing values

In [47]:
#Series function is used to create arrays
data = pd.Series([1., -999., 2., -999., -1000., 3.])

data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [50]:
import numpy as np
#replace -999. with NaN values
data.replace(-999, np.nan, inplace=True)

data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
#replace multiple values at once

data = pd.Series([1., -999., 2., -999., -1000., 3.])

data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

#### Renaming 

In [54]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [57]:
data.rename(index={'Ohio':'SanF'}, columns={"one":"one_p", "two":"two_p"}, inplace=True)

data

one_p  two_p  three  four
SanF          0      1      2     3
Colorado      4      5      6     7
New York      8      9     10    11

In [59]:
#Using string function

x = data.rename(index=str.upper, columns=str.title)

x

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLORADO      4      5      6     7
NEW YORK      8      9     10    11

#### Categorize (Bin) continuous variables

In [60]:
ages = np.array([20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32])

In [61]:
ages

array([20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32])

In [62]:
#We'll divide the ages into bins such as 18-25, 26-35,36-60 and 60 and above.

bins = np.array([18, 25, 35, 60, 100])
category = pd.cut(ages, bins)

In [63]:
category #'(' means the value is included in the bin, '[' means the value is excluded

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [67]:
ages

array([20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32])

In [68]:
bins

array([ 18,  25,  35,  60, 100])

In [69]:
category

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [83]:
pd.cut(ages,bins,right=False) #right - Indicates whether bins includes the rightmost edge or not.

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [80]:
category.labels

/Users/ainurafifah/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [81]:
category.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [82]:
pd.value_counts(category)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [84]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_category = pd.cut(ages, bins, labels=bin_names)

pd.value_counts(new_category)

Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [85]:
#calculate cumulative sum

pd.value_counts(new_category).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

#### Grouping data and Creating pivots

##### Grouping data

In [87]:
df = pd.DataFrame({'key1': ['a', 'a', 'b', 'b', 'a'],
                   'key2': ['one', 'two', 'one', 'two', 'one'],
                   'data1': np.random.randn(5),
                   'data2': np.random.randn(5)
                  })

df

data1     data2 key1 key2
0  0.667767  0.268309    a  one
1 -0.829084  0.365079    a  two
2 -0.153942  0.039996    b  one
3  1.406985  0.050641    b  two
4  0.481185  0.795837    a  one

In [92]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])

grouped.mean()

key1
a    0.106623
b    0.626521
Name: data1, dtype: float64

In [93]:
#how to slice the data frame.
dates = pd.date_range('20130101', periods=6) #date start, number of periods to generate
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

df

A         B         C         D
2013-01-01 -0.160905  1.063228  0.097120  1.832589
2013-01-02 -0.265111  0.725770 -1.904870  0.319954
2013-01-03 -0.332898  0.894869 -0.287824  0.879429
2013-01-04 -0.422337 -1.711638 -0.630504  0.488289
2013-01-05 -0.184436  1.271899  1.448128  0.740569
2013-01-06 -1.644588 -0.828543  0.420163 -0.043987

In [94]:
df[:3]

A         B         C         D
2013-01-01 -0.160905  1.063228  0.097120  1.832589
2013-01-02 -0.265111  0.725770 -1.904870  0.319954
2013-01-03 -0.332898  0.894869 -0.287824  0.879429

In [95]:
#slice based on date range

df['20130101':'20130104']

A         B         C         D
2013-01-01 -0.160905  1.063228  0.097120  1.832589
2013-01-02 -0.265111  0.725770 -1.904870  0.319954
2013-01-03 -0.332898  0.894869 -0.287824  0.879429
2013-01-04 -0.422337 -1.711638 -0.630504  0.488289

In [97]:
#slice based on column names

df.loc[:,['A','B']]

A         B
2013-01-01 -0.160905  1.063228
2013-01-02 -0.265111  0.725770
2013-01-03 -0.332898  0.894869
2013-01-04 -0.422337 -1.711638
2013-01-05 -0.184436  1.271899
2013-01-06 -1.644588 -0.828543

In [99]:
#Take it up a notch
df.loc['20130102':'20130103', ['A','B']]

A         B
2013-01-02 -0.265111  0.725770
2013-01-03 -0.332898  0.894869

In [100]:
#slicing based on index of columns
df.iloc[3] #returns 4th row (index is 3rd)


A   -0.422337
B   -1.711638
C   -0.630504
D    0.488289
Name: 2013-01-04 00:00:00, dtype: float64

In [103]:
df.iloc[1:4, 0:2] #Returns range (row, column) 

A         B
2013-01-02 -0.265111  0.725770
2013-01-03 -0.332898  0.894869
2013-01-04 -0.422337 -1.711638

In [104]:
df.iloc[[1,5],[0,2]] #returns THE range and columns

A         C
2013-01-02 -0.265111 -1.904870
2013-01-06 -1.644588  0.420163

In [109]:
#Boolean indexing based on column values
df[df.B > 1]

A         B         C         D
2013-01-01 -0.160905  1.063228  0.097120  1.832589
2013-01-05 -0.184436  1.271899  1.448128  0.740569

In [112]:
#copy dataset using copy function
df2 = df.copy()

df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01 -0.160905  1.063228  0.097120  1.832589    one
2013-01-02 -0.265111  0.725770 -1.904870  0.319954    one
2013-01-03 -0.332898  0.894869 -0.287824  0.879429    two
2013-01-04 -0.422337 -1.711638 -0.630504  0.488289  three
2013-01-05 -0.184436  1.271899  1.448128  0.740569   four
2013-01-06 -1.644588 -0.828543  0.420163 -0.043987  three

In [115]:
#select rows based on column values
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03 -0.332898  0.894869 -0.287824  0.879429   two
2013-01-05 -0.184436  1.271899  1.448128  0.740569  four

In [117]:
df.query('A > C')

A         B         C         D
2013-01-02 -0.265111  0.725770 -1.904870  0.319954
2013-01-04 -0.422337 -1.711638 -0.630504  0.488289

In [118]:
df.query('A < B | C > A')

A         B         C         D
2013-01-01 -0.160905  1.063228  0.097120  1.832589
2013-01-02 -0.265111  0.725770 -1.904870  0.319954
2013-01-03 -0.332898  0.894869 -0.287824  0.879429
2013-01-05 -0.184436  1.271899  1.448128  0.740569
2013-01-06 -1.644588 -0.828543  0.420163 -0.043987

##### Pivot
Pivot tables are extremely useful in analyzing data using a customized tabular format. 

In [120]:
data = pd.DataFrame({'group':['a']*3 + ['b']*3 + ['c']*3,
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
                    })

data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [122]:
#calculate means of each group

data.pivot_table(values='ounces', index='group', aggfunc=np.mean)

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [126]:
#calculate count by each group

data.pivot_table(values='ounces', index='group', aggfunc='count')

#values : columns to aggregate
#index : the grouper

ounces
group        
a           3
b           3
c           3